name: "Create Issues from TODOs"
on:
  pull_request:
    branches:
      - main
permissions:
  contents: read
  issues: write
jobs:
  build:
    runs-on: "ubuntu-latest"
    permissions:
      issues: write
    steps:
      - uses: "actions/checkout@v4"
      - name: "Create GitHub Issues from TODO comments"
        uses: "alstr/todo-to-issue-action@v5"
        with:
          AUTO_ASSIGN: "true"
          CLOSE_ISSUES: "true"